### ISSUE TITLE
Using relative dimensions

### ISSUE THREAD

**Issue by getimo** [jkphl/node-iconizr#8]
Hi, thanks for iconizr!

I'm not a developer but would like to use your service. Since I read about SVG - sprites in particular - I'm really interested in creating an icon set based on a SVG-sprite. These are the ressources I read:

- http://css-tricks.com/svg-sprites-use-better-icon-fonts/
- http://css-tricks.com/svg-symbol-good-choice-icons/
- http://www.smashingmagazine.com/2012/01/16/resolution-independence-with-svg/ (that's great!)

I tried many variations but didn't get a satisfying solution (maybe because I'm not a developer). After finding iconizr I thought that would be my personal solution but then I realized that I can't resize the icons with CSS - at least very complicated. Plus: the generated SVG-sprite is very huge (~450KB) which contains pixel dimensions - not em. I think that's the key-issue.

I think iconizr would be a great tool for designer like me :)

PS: You can see my icons here: http://goo.gl/AEHVOB
PPS: My first posting here on Github, maybe that's not the way is is supposed to be to start a discussion about that functionality - sorry!

getimo

**Comment by jkphl** [comment]
Hi @getimo,

I know it's been a lot of time, but still I wouldn't want to miss answering you. First of all, thanks for posting your issue (and a Happy New Year by the way)! To answer some of your questions:

1. I don't know of any SVG authoring tool that let's you define relative dimension for your SVG (i.e. `em` or alike). But besides, as SVG is a vector format and thus losslessly scalable by definition, using absolute dimensions shouldn't be an issue anyway, as you can always scale the drawing.

2. You say "I can't resize the icons with CSS - at least very complicated". What's so complicated about that? Would you mind sharing your efforts?

3. "Huge" SVG files shouldn't be an issue as well. First, their binary counterparts (PNG etc.) are mostly even bigger. Second, SVG compress really well (you should dig into `DEFLATE` compression for Apache webservers for example).

4. Finally, one last thing: I don't really understand what's the question or proposal in your issue? What do you expect me to answer or do in response?

I'll close the issue for now, but please feel free to re-open it in case you want to discuss this further! :)

Cheers,
Joschi
