### ISSUE TITLE
pngcrush-bin dependency outdated

### ISSUE THREAD

**Issue by mechanicalduck** [jkphl/node-iconizr#9]
The pngcrush-bin dependency in package.json is outdated.
npm module node-grunt is also affected as it got npm module (node-)iconizr as depenceny.

The outdated pngcrush-bin expects a specific GLIBC library which is not present on many systems and fail, also the build source url is incorrect.
````
[...]
Creating PNG versions of 2 SVG images (including the sprite) ...
{ [Error: Command failed: [...]/node_modules/iconizr/node_modules/pngcrush-bin/vendor/pngcrush: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by [...]/node_modules/iconizr/node_modules/pngcrush-bin/vendor/pngcrush)] killed: false, code: 1, signal: null }

Done, without errors.
[...]
````
Although no error was indicated in the end of the task, only one PNG was generated, the others missing and the style files weren't written.

This can be solved however by forcing iconizr to use the latest stable pngcrush-bin dependency:
````
(cwd is project dir)
$ rm -r ./node_modules/iconizr/node_modules/pngcrush-bin/
$ npm install pngcrush-bin
````

````
Creating PNG versions of 2 SVG images (including the sprite) ...
{ [Error: Command failed: ] killed: false, code: 1, signal: null }
````

The pngcrush-bin pngcrush command would work again, the PNGs are created - 
however, there still seems to be at least some misinterpretation of its exit code as the command is remarked as 'failed' during iconizr run and the subsequent css/sass/stylus/... files aren't written.

So bumping the pngcrush-bin dependency to latest stable + adjusting its invocation in iconizr will solve this issue.

Thank you in advance.
With best regards.

**Comment by jkphl** [comment]
Hey @mechanicalduck,

I know a lot of time has passed — thanks for your patience! I just updated the dependencies and released a new version. Could you please check if this works for you (again)? I'll close the issue for now, but please feel free to re-open in case of any further problems.

I'll start rewriting iconizr from scratch during the next days, so stay tuned in any case.

Besides that, Happy New Year! :)

Cheers,
Joschi
